apiVersion: apps/v1
kind: Deployment #Deployment kubernetes and collection

metadata:
   name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
template:
   metadata:
     labels:
       app: nginx    
   spec:
    containers:
     -name: nginx-container            
    image: nginx:latest
